### ISSUE TITLE
Add a new model for course access request for payed courses

### ISSUE THREAD

**Issue by ermias111** [Nathan-G1/ak#13]
add a model that contains course access request information for those who paid for a specific course.
the model includes {
    StudentId : required,
    CourseId : required,
    phoneNumber: "", (for those who payed with cbe birr)
    receiptImage: "", (for those who transfered to the account manually)
    requestDate: date,
    coursePrice: ''
} add some if you think it's not enough

**Comment by nathan-g1** [comment]
@ermias111 what I finally did is, I associated the new model with course model, and now we can find all course requests from the corresponding course, and also if we want to create a new request we can do so from the selected course.

You can actually understand it if u see the change on the course model API

**Comment by nathan-g1** [comment]
So I am closing this issue now, if it is not resolved you'll recreate it
