### ISSUE TITLE
Add missing fields in some models

### ISSUE THREAD

**Issue by ermias111** [Nathan-G1/ak#14]
**Field**          -->    **model**

isFree : boolean --> course
courseFee : int --> course 
isApproved : bool--> courseRequest
studentFirstName & studentLastName : string--> courseRequest

**Comment by nathan-g1** [comment]
@ermias111 will it be tedious getting Student first & last name from their Id?

**Comment by ermias111** [comment]
> @ermias111 will it be tedious getting Student first & last name from their Id?

Yes it will, since we are going to have list of course requests it will be tedious to get each student's name for each list item.

**Comment by ermias111** [comment]
> @ermias111 will it be tedious getting Student first & last name from their Id?

we might also need to add course title and user Image
