### ISSUE TITLE
Edit some fields in AkUser and Courses model

### ISSUE THREAD

**Issue by ermias111** [Nathan-G1/ak#15]
- [ ] change enrolledStudents field from string to array of string in courses model 

- [x]  remove whatToLearn field from couses model
- [x] change requirements field from array to string in courses model

**Comment by nathan-g1** [comment]
One question @ermias111 enrolledStudents is actually a number now?

**Comment by nathan-g1** [comment]
- [x]  remove whatToLearn field from couses model
- [x] change requirements field from array to string in courses model

**Comment by ermias111** [comment]
@Nathan-G1 ok we can let the enrolledStudents field stay like it is now. i saw we have an api call (courses/{id}/akuser) that give us chance to manage enrolled students per each course.

**Comment by nathan-g1** [comment]
nice  👍
